services:
  huawei-lte-exporter:
    image: ghcr.io/imbo-fr/huawei-lte-exporter:latest@sha256:3076b9eedad44b076eb1ea106e7e6dd9ef2902d28febdef6b3667d0f092b8e5c
    # build: .   # ← uncomment for local dev
    container_name: huawei-lte-exporter
    environment:
      ROUTER_URL:     "http://192.168.8.1/"
      ROUTER_USER:    "admin"
      ROUTER_PASS:    "${ROUTER_PASS}"
      EXPORTER_PORT:  "9898"
      LOG_LEVEL:      "INFO"
      SCRAPE_TIMEOUT: "10"
    restart: unless-stopped
    ports:
      - "9898:9898"